# Generated by Django 4.2.7 on 2025-07-11 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FormularioHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_hash', models.PositiveIntegerField(unique=True)),
                ('tipo', models.CharField(choices=[('PROCEDIMIENTO', 'Procedimiento'), ('VUELO', 'Vuelo')], default='PROCEDIMIENTO', max_length=20)),
                ('procedimiento', models.CharField(max_length=300)),
                ('imagenes', models.PositiveIntegerField(default=0)),
                ('clips', models.PositiveIntegerField(default=0)),
                ('audio', models.PositiveIntegerField(default=0)),
                ('texto', models.PositiveIntegerField(default=0)),
                ('varios', models.PositiveIntegerField(default=0)),
                ('peso_total_bytes', models.BigIntegerField(default=0)),
                ('peso_total_formateado', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('FINALIZADO', 'Finalizado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formulario Hash',
                'verbose_name_plural': 'Formularios Hash',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Jerarquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('abreviatura', models.CharField(max_length=20)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden jerárquico (menor = mayor jerarquía)')),
            ],
            options={
                'verbose_name': 'Jerarquía',
                'verbose_name_plural': 'Jerarquías',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TipoProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Procedimiento',
                'verbose_name_plural': 'Tipos de Procedimientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Oficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficiales', to='core.destino')),
                ('jerarquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficiales', to='core.jerarquia')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oficial',
                'verbose_name_plural': 'Oficiales',
                'ordering': ['jerarquia__orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='core.formulariohash')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Formulario',
                'verbose_name_plural': 'Historiales de Formularios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='formulariohash',
            name='oficial_entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_entregados', to='core.oficial'),
        ),
        migrations.AddField(
            model_name='formulariohash',
            name='oficial_recibe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_recibidos', to='core.oficial'),
        ),
        migrations.AddField(
            model_name='formulariohash',
            name='tipo_procedimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoprocedimiento'),
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_orden', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=500)),
                ('extension', models.CharField(max_length=20)),
                ('peso', models.BigIntegerField()),
                ('peso_formateado', models.CharField(blank=True, max_length=50)),
                ('hash_sha256', models.CharField(blank=True, max_length=64)),
                ('ruta_original', models.TextField(blank=True)),
                ('fecha_modificacion_original', models.DateTimeField(blank=True, null=True)),
                ('tipo_mime', models.CharField(blank=True, max_length=100)),
                ('es_imagen', models.BooleanField(default=False)),
                ('es_video', models.BooleanField(default=False)),
                ('es_audio', models.BooleanField(default=False)),
                ('es_documento', models.BooleanField(default=False)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='core.formulariohash')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'ordering': ['formulario', 'nro_orden'],
                'unique_together': {('formulario', 'nro_orden')},
            },
        ),
    ]
