# Generated by Django 4.2.7 on 2025-07-11 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioCustodia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_custodia', models.PositiveIntegerField(unique=True)),
                ('caratula', models.CharField(max_length=500)),
                ('sumario', models.CharField(blank=True, max_length=300)),
                ('juzgado_fiscalia', models.CharField(blank=True, max_length=300)),
                ('secretaria', models.CharField(blank=True, max_length=300)),
                ('otra_informacion', models.TextField(blank=True)),
                ('identificacion_material', models.TextField(blank=True)),
                ('breve_descripcion', models.TextField(blank=True)),
                ('fecha_hora_incidente', models.DateTimeField()),
                ('fecha_hora_custodia', models.DateTimeField(auto_now_add=True)),
                ('nro_control', models.PositiveIntegerField(default=1)),
                ('nro_orden', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('FINALIZADO', 'Finalizado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('nro_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custodias', to='core.formulariohash')),
            ],
            options={
                'verbose_name': 'Formulario de Custodia',
                'verbose_name_plural': 'Formularios de Custodia',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCustodia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('formulario_custodia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='core.formulariocustodia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Custodia',
                'verbose_name_plural': 'Historiales de Custodia',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PersonalCustodia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(help_text='Función del oficial en la custodia', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción de las actividades realizadas')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('fecha_hora_intervencion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('formulario_custodia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='core.formulariocustodia')),
                ('oficial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.oficial')),
            ],
            options={
                'verbose_name': 'Personal de Custodia',
                'verbose_name_plural': 'Personal de Custodia',
                'ordering': ['formulario_custodia', 'orden'],
                'unique_together': {('formulario_custodia', 'orden')},
            },
        ),
    ]
