# Generated by Django 4.2.7 on 2025-07-12 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_formulariocustodia_historialcustodia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historialformulario",
            name="formulario",
        ),
        migrations.RemoveField(
            model_name="historialformulario",
            name="usuario",
        ),
        migrations.DeleteModel(
            name="HistorialCustodia",
        ),
        migrations.DeleteModel(
            name="HistorialFormulario",
        ),
    ]
