# Generated by Django 4.2.7 on 2025-07-14 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_historialformulario_formulario_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='archivo',
            unique_together={('formulario', 'hash_sha256'), ('formulario', 'nro_orden')},
        ),
    ]
