# Generated by Django 4.2.7 on 2025-07-14 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_unique_constraint_file_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oficial',
            options={'ordering': ['-jerarquia__orden', 'nombre'], 'verbose_name': 'Oficial', 'verbose_name_plural': 'Oficiales'},
        ),
        migrations.AlterField(
            model_name='oficial',
            name='jerarquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oficiales', to='core.jerarquia'),
        ),
    ]
