# Generated by Django 4.2.7 on 2025-07-16 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_oficial_options_alter_oficial_jerarquia'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariocustodia',
            name='destino_custodia',
            field=models.ForeignKey(blank=True, help_text='Destino donde se realiza la custodia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodias', to='core.destino'),
        ),
        migrations.AddField(
            model_name='personalcustodia',
            name='destino_intervencion',
            field=models.ForeignKey(blank=True, help_text='Destino específico donde interviene el oficial en esta custodia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervenciones_custodia', to='core.destino'),
        ),
    ]
